application: writing-diary
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: 2.5.2

builtins:
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /gae_mini_profiler/static
  static_dir: gae_mini_profiler/static
- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application

- url: /.*
  script: main.app
